### PR TITLE
Added manual_control Example

### PR DESCRIPTION
**Pull request by GriffinMack**
Added a basic example showcasing the use of the manual control plugin. 

I could not find a way to implement joystick support without importing another pip package, so I decided to show manual input using some hard coded test input vectors. I believe this gets the point across, but the controls are very spastic (though it is fun to watching using jMAVsim).

### CODE REVIEW

**Review by JonasVautherin — APPROVED** [review]
Yes looks nice! Thanks

**Comment by julianoes** [comment]
Thanks a lot @GriffinMack!

**Comment by kennethakiti1** [comment]
@GriffinMack I have been trying to run the manual_control code on my PX4 drone, however, this doesn't seem to work, the drone just goes up to takeoff heights and then lands immediately. 

if anyone else has tried it, can you give me a recommendation?

**Comment by kennethakiti1** [comment]
@GriffinMack I have been trying to run the manual_control code on my PX4 drone, however, this doesn't seem to work, the drone just goes up to takeoff heights and then lands immediately. 

if anyone else has tried it, can you give me a recommendation?

**Pull request merged**
