### PR TITLE
Shell plugin

### PR DESCRIPTION
**Pull request by irsdkv**
Modified autogen output: https://github.com/mavlink/MAVSDK-Python/pull/120/files#diff-3733b74e206e0bb2c4c9c20c6b22cfc0R307

Usage:
```python
shm = ShellMessage(True, 1000, text)
result = await system.shell.set_shell_message(shm)
```

### CODE REVIEW

**Comment by JonasVautherin** [comment]
You won't need to modify the autogenerated code if you change the proto file as per my review in MAVSDK-Proto, I believe :wink:

**Comment by JonasVautherin** [comment]
@irsdkv: I pushed fixes for the bug you reported. It seems to work, but I don't have the corresponding `mavsdk_server`. Would you mind trying that and letting me know if that's better?

Note: you'll have to run `run_protoc.sh` again :wink:.

**Comment by irsdkv** [comment]
> @irsdkv: I pushed fixes for the bug you reported.

I'm tested it. Yes its works, cool! :)

**Comment by JonasVautherin** [comment]
Obviously now it conflicts because I just merged the Mocap PR :stuck_out_tongue_winking_eye:

**Comment by irsdkv** [comment]
Done :)

**Pull request merged**
