### PR TITLE
Fix Follow Me example

### PR DESCRIPTION
**Pull request by KarthiAru**
Fix Follow Me example by explicitly setting a non-zero value for absolute_altitude_m in target_location

### CODE REVIEW

**Comment by KarthiAru** [comment]
@julianoes Please check and approve this.
This is related to a similar issue in the C++ SDK https://github.com/mavlink/MAVSDK/issues/2216

**Review by julianoes — APPROVED** [review]
Thanks!

**Comment by julianoes** [comment]
@KarthiAru do you mind fixing style: https://github.com/mavlink/MAVSDK-Python/actions/runs/10200136185/job/28238813887?pr=722

**Comment by KarthiAru** [comment]
@julianoes Done

**Pull request merged**
