### PR TITLE
Update __init__.py to reflect geofence proto

### PR DESCRIPTION
**Pull request by coderkalyan**
Here is an updated `__init__.py` reflecting the new Geofence gRPC binding I have been working on. For this PR to be of any use, https://github.com/mavlink/MAVSDK-Proto/pull/89 must be merged first so the `.proto` files are introduced.

### CODE REVIEW

**Comment by coderkalyan** [comment]
@JonasVautherin no problem :) Sorry, I didn't understand exactly what you want me to do to the submodule?

**Comment by JonasVautherin** [comment]
So once your `geofence.proto` PR is merged, you'll be able to go in `proto/` in MAVSDK-Python, which is a git submodule pointing to MAVSDK-Proto. And there you can just `git checkout master && git pull`, or something equivalent, and add that change to this PR.

Because this PR is useless if the `proto/` submodule does not contain the `geofence.proto` file :-).

Does that help?

**Comment by coderkalyan** [comment]
Yep! Let me do that now

**Comment by coderkalyan** [comment]
@JonasVautherin I have updated the submodules. I also took the chance to update the submodule remote from DronecodeSDK/DronecodeSDK-Proto to mavlink/MAVSDK-Proto (I know the first one redirects). If you don't want this I can remove it.

**Comment by JonasVautherin** [comment]
Seems good! I'd like to merge that after https://github.com/mavlink/MAVSDK/pull/805, otherwise it will just throw `UNIMPLEMENTED` and that will be confusing.

**Pull request closed without merging**
