### PR TITLE
Updated raw mission example + removed deprecations

### PR DESCRIPTION
**Pull request by ShafSpecs**
- Updated [MAV_FRAME](https://mavlink.io/en/messages/common.html#MAV_FRAME) command from 6 (deprecated) to 3 (newly updated WGS84 + rel. system)

- Also added a few comments to make comprehension easier

- Refactored file

### CODE REVIEW

**Review by JonasVautherin — DISMISSED** [review]

**Review by julianoes — APPROVED** [review]
Thanks!

**Comment by julianoes** [comment]
Looks like it just needs the style fixes and then it's good to go.

**Comment by ShafSpecs** [comment]
> Looks like it just needs the style fixes and then it's good to go.

Made the styling fixes :+1:

**Review by julianoes — APPROVED** [review]

**Comment by julianoes** [comment]
Thanks!

**Pull request merged**
