### PR TITLE
firware_version.py update

### PR DESCRIPTION
**Pull request by arpitpara**
The request adds on the required function according to recent update of mavsdk_server 1.4.13.
I am adding the respective issue link for the reference.
[Issue link](https://github.com/mavlink/MAVSDK-Python/issues/556)
Mavsdk fix - https://github.com/mavlink/MAVSDK/pull/2006

### CODE REVIEW

**Comment by JonasVautherin** [comment]
My understanding was that this was fixed in MAVSDK, so that it does not need to be changed in the examples :thinking:. Am I missing something?

**Comment by arpitpara** [comment]
> My understanding was that this was fixed in MAVSDK, so that it does not need to be changed in the examples thinking. Am I missing something?
> 
> I mean, what's the point of waiting 1.5s in MAVSDK if you then wait 2s in the example?

Actually, even I thought so
Let me check by updating the masdk version.

**Comment by arpitpara** [comment]
mavsdk version is still 1.4.13 in MAVSDK Python

**Comment by arpitpara** [comment]
Yeah It is working with newer version.
Sorry for bothering. Just started in this stuff so thanks for the remarks.

**Comment by arpitpara** [comment]
Thanks

**Comment by julianoes** [comment]
Fixed in 1.4.5.

**Pull request closed without merging**
