### PR TITLE
Winch and Gripper plugins

### PR DESCRIPTION
**Pull request by potaito**
## Related PRs
- Proto: https://github.com/mavlink/MAVSDK-Proto/pull/308
- MAVSDK: https://github.com/mavlink/MAVSDK/pull/1958
- MAVSDK-Python: https://github.com/mavlink/MAVSDK-Python/pull/545  **(this PR)**

## Description
Adds the winch and gripper plugins also to MAVSDK-Python.

The example scripts are a bit tricky, since there is currently no simulation counterpart against which they can be used. They work in the sense that they send the corresponding commands, but MAVSDK will not receive an ACK if there is no winch or gripper component connected to MAVSDK. I don't know how we want to handle this for example scripts. 

## TODO
After updating the proto submodule and regenerating the python part, I got quite a lot of changes across the board and I'm not sure what needs to be committed:
```
 mavsdk/action.py                |   8 +++++
 mavsdk/action_pb2.py            |  14 ++++-----
 mavsdk/follow_me.py             | 142 ++++++++++++++++++++++++++++++++++++++++++++++++--------------------------------------
 mavsdk/follow_me_pb2.py         |  94 +++++++++++++++++++++++++++++----------------------------
 mavsdk/geofence.py              | 275 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++--------------------------------
 mavsdk/geofence_pb2.py          |  71 +++++++++++++++++++++++++++++--------------
 mavsdk/geofence_pb2_grpc.py     |   4 +--
 mavsdk/gimbal.py                |   2 +-
 mavsdk/info.py                  |  92 +++++++++++++++++++++++++++++++++++++++++++++++++++++---
 mavsdk/info_pb2.py              |  19 +++++++-----
 mavsdk/log_files.py             |  46 ----------------------------
 mavsdk/log_files_pb2.py         |  42 ++++++++++----------------
 mavsdk/log_files_pb2_grpc.py    |  34 ---------------------
 mavsdk/mission.py               | 108 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++---
 mavsdk/mission_pb2.py           |  39 +++++++++++++-----------
 mavsdk/mission_raw.py           | 120 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 mavsdk/mission_raw_pb2.py       | 146 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++--------------------------------
 mavsdk/mission_raw_pb2_grpc.py  |  70 +++++++++++++++++++++++++++++++++++++++++++
 mavsdk/offboard.py              |   8 +++++
 mavsdk/offboard_pb2.py          |  10 +++----
 mavsdk/source/plugins/index.rst |   2 ++
 mavsdk/telemetry.py             | 224 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++----
 mavsdk/telemetry_pb2.py         | 460 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++------------------------------------------------------------------------------------------------------------------
 mavsdk/telemetry_pb2_grpc.py    | 130 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++---------
 mavsdk/transponder.py           |  54 ++++++++++++++++++++++++++++++++-
 mavsdk/transponder_pb2.py       |  26 +++++++++-------
 mavsdk/winch.py                 | 452 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 mavsdk/winch_pb2.py             | 138 ++++++++++++++++++++++++++++++++++++++++++++++++++++++------------------------------
 mavsdk/winch_pb2_grpc.py        |  34 +++++++++++++++++++++
 29 files changed, 2205 insertions(+), 659 deletions(-)

```

I guess all changes need to be committed?

Please don't merge before I squashed the commits :)

### CODE REVIEW

**Comment by potaito** [comment]
I cleaned up the commits and rebased on top of the main branch. MAVSDK Server was recently just updated to a version that already contains the corresponding Proto changes for winches and grippers. So I did not have to touch `MAVSDK_SERVER_VERSION`.

**Comment by JonasVautherin** [comment]
So this is meant to come with MAVSDK v2, right?

**Comment by julianoes** [comment]
Yes, it will be part of v2.

**Comment by JonasVautherin** [comment]
Sure, I was just wondering if @potaito was expecting it in 1.4 or not :sweat_smile:

**Comment by julianoes** [comment]
I guess this could now go in, now that we have 2.0.

**Comment by potaito** [comment]
Great, thank you @julianoes :)

**Comment by julianoes** [comment]
Thank you :smile:

**Pull request merged**
