### PR TITLE
Transponder plugin

### PR DESCRIPTION
**Pull request by DoppleGangster**
I'm attempting to add the transponder plugin. When I run my example I receive an error:

>   File "transponder.py", line 17, in print_transponders
    async for transponder in drone.transponder.transponder():
  File "/home/drone1/Documents/MAVSDK-Python/mavsdk/transponder.py", line 591, in transponder
    async for response in transponder_stream:
  File "/home/drone1/.local/lib/python3.8/site-packages/aiogrpc/utils.py", line 154, in __anext__
    return await asyncio.shield(self._next_future)
  File "/home/drone1/.local/lib/python3.8/site-packages/aiogrpc/utils.py", line 145, in cb
    fut.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/drone1/.local/lib/python3.8/site-packages/aiogrpc/utils.py", line 131, in _next
    return next(self._iterator)
  File "/home/drone1/.local/lib/python3.8/site-packages/grpc/_channel.py", line 416, in __next__
    return self._next()
  File "/home/drone1/.local/lib/python3.8/site-packages/grpc/_channel.py", line 786, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = ""
	debug_error_string = "{"created":"@1617718871.372854475","description":"Error received from peer ipv6:[::1]:50051","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"","grpc_status":12}"
>

I'm assuming a step is missing to get the plugin to operate correctly in for python. Some guidance would be greatly appreciated.

Thanks!

### CODE REVIEW

**Comment by julianoes** [comment]
@DoppleGangster sorry, we forgot to add the transponder plugin to the server. This has to be done manually in:
- https://github.com/mavlink/MAVSDK/blob/main/src/mavsdk_server/src/grpc_server.h
- https://github.com/mavlink/MAVSDK/blob/main/src/mavsdk_server/src/grpc_server.cpp
- https://github.com/mavlink/MAVSDK/blob/main/src/mavsdk_server/src/CMakeLists.txt#L3
- https://github.com/mavlink/MAVSDK/blob/main/src/mavsdk_server/src/CMakeLists.txt#L45-L71

**Comment by JonasVautherin** [comment]
Whoops, sorry... I think it's a classic with new plugins :sweat_smile:

**Comment by DoppleGangster** [comment]
No problem thanks again again for the help. I've tested the update and I'm now getting the transponder data with MAVSDK-Python. I'm created the pull request for MAVSDK updates.

**Review by JonasVautherin — APPROVED** [review]
Thanks!

**Comment by DoppleGangster** [comment]
No problem thanks again for all your help!

**Pull request merged**
