### PR TITLE
Examples: Add files via upload

### PR DESCRIPTION
**Pull request by farhangnaderi**
In honor of this PR: https://github.com/mavlink/MAVSDK-Python/pull/558

cc: @julianoes @afwilkin

### CODE REVIEW

**Comment by julianoes** [comment]
Thanks @farhangnaderi, this worked. Let me know what you think about my changes, and make sure to test again.

I tried to run it but it just stalled for me.

**Comment by farhangnaderi** [comment]
Thanks for your time Julian. Tested and made some small changes, let me know if you are happy with it! :D

**Review by julianoes — APPROVED** [review]
Nice, that looks good now. Does it work for you?

**Comment by farhangnaderi** [comment]
> Nice, that looks good now. Does it work for you?

Yes Julian, tested on SITL:
image

**Comment by julianoes** [comment]
Nice! Thanks!

**Review by julianoes — APPROVED** [review]

**Comment by farhangnaderi** [comment]
Thanks a bunch for your help!

**Pull request merged**
