### PR TITLE
Added Failure Plugin

### LINKED ISSUE #254: Failure Plugin Missing
I noticed that there are generated files for the Failure plugin, but it was not made available in system.
(I am a bit confused is the code in System supposed to be auto-generated as well?)

I created a PR https://github.com/mavlink/MAVSDK-Python/pull/253
which makes the Plugin available but then I noticed when using it I get:

```
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:                              
        status = StatusCode.UNIMPLEMENTED  
```
I was assuming that all functionality from the core MAVSDK would be auto-generated for Python.

### PR DESCRIPTION
**Pull request by petergerten**
Resolves #254.

### CODE REVIEW

**Review by JonasVautherin — CHANGES_REQUESTED** [review]
Looks good, thanks! However, and as mentioned in #254, the plugin needs to be enabled in `mavsdk_server` first. We should merge this after it gets merged there, if that makes sense to you?

**Comment by julianoes** [comment]
@JonasVautherin did we already add failure to mavsdk_server by now?

**Comment by petergerten** [comment]
@julianoes sorry, I am currently very busy and did not have time to do this yet.

**Review by JonasVautherin — APPROVED** [review]
I think this can now be merged, to be released with the next MAVSDK-C++ release (`v0.35.0`).

@julianoes: agreed?

**Review by julianoes — APPROVED** [review]

**Pull request merged**
